### ISSUE TITLE
Dummy Load on RT-65B

### ISSUE THREAD

**Issue by danko79** [jbilander/Amiga_Mean_Well_RT-50B_PSU_Mount#1]
Hi, i need info, have for spare a Mean Well RT-65B, the power resistors is the same to RT-50B?
100 Ohm, 3 watt capable resistor is perfect for the -12V
47 Ohm, 5 watt capable resistor is suitable for the 12V
Thanks

**Comment by jbilander** [comment]
Hi, I don't think a dummy load is needed on newer Mean Well PSU:s. Check your datasheet about minimum draw requirements. On this datasheet...
 
https://www.meanwell-web.com/content/files/pdfs/productPdfs/MW/Rt-65/RT-65-spec.pdf

...it says: 0 ~ 8A, 0 ~ 3.5A, 0 ~ 1A for the three outputs, so it seems there can be zero load on +12V and -12V and it will still regulate properly.

Also notice that the 65B has different dimensions than the 50B that the mounting bracket is designed for.

https://www.meanwell-web.com/content/files/pdfs/productPdfs/MW/Rt-50/RT-50-spec.pdf

**Comment by danko79** [comment]
Hi ok, many thanks.
